### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by bogdal**
This PR adds docker support. This configuration doesn't build front-end assets yet but it allows to work with project in isolated environment.

### CODE REVIEW

**Comment by patrys** [comment]
Is it meant for production or dev use?

**Comment by bogdal** [comment]
As far as the project's code is concerned, this configuration handles both envs.

**Comment by patrys** [comment]
I'm asking since production should probably use `exrm` instead of `mix`.

**Comment by bogdal** [comment]
Thanks for the tip. In this case it will be better to prepare two separate configurations.

**Comment by bogdal** [comment]
As the prod env needs more love (like ssl support), I suggest use the current conf only for dev. Prod env we will handle later.

**Pull request merged**
